baseurl      = "https://tokochiz.github.io/"
title        = "tokochi'z website"

theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "tokochiz"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "tokochi'z website"
keywords = "blog, developer, personal, website, tokochiz"
info = ["ctokoyod", "Infrastructure engineer"]
avatarURL = "images/icon_tokochiz.jpeg"
dateFormat = "January 2, 2006"
since = 2025
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = ["css/mint-green.css"]
#customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/tokochiz/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 2
url = "https://twitter.com/tokochizu/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/chihiro-tokoyoda"

[[params.social]]
name = "Zenn"
icon = "fa-brands fa-zenn fa-2x"
weight = 4
url = "https://zenn.dev/tokochiz"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

# [languages.ja]
# languageName = ":japanese:"
# title = "tokochiz"

# [languages.ja.params]
# author = "とこちず"
# info = ""
# description = ""
# keywords = ""

# [[languages.ja.menu.main]]
# name = "Sobre"
# weight = 1
# url = "about/"

# [[languages.ja.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.ja.menu.main]]
# name = "Projetos"
# weight = 3
# url = "projects/"

# [[languages.ja.menu.main]]
# name = "Contato"
# weight = 5
# url = "contact/"
